### ISSUE TITLE
All posts in feed "updated" on deploy

### ISSUE THREAD

**Issue by tfausak** [hmemcpy/hmemcpy.com#7]
I noticed that every item in your feed has its `<updated>` element set to the time of the last deploy. For example: 

https://github.com/hmemcpy/hmemcpy.com/blob/1f3ad90996b185eaf48367cdbd2fe802eef8e98e/atom.xml#L24

It's not a problem exactly, but it does seem a little strange to me. Was this on purpose? If so, what's the rationale? If not, would you mind changing this behavior? Thanks!

**Comment by hmemcpy** [comment]
Oh wow, thanks for letting me know! To be honest, I didn't even realize people were using RSS for subscriptions :)
I'll look into it, to see if it can be disabled (it's the blog generator that adds this, I imagine). I can imagine this can get spammy on each redeploy.

**Comment by tfausak** [comment]
Thanks! 

I like to use RSS because I follow a lot of blogs that don't announce posts any other way. In fact I'm working on a Haskell feed aggregator to make my life as the editor of Haskell Weekly easier 😄 You're included because one of your posts was featured in Haskell Weekly a while ago. Check it out! https://github.com/haskellweekly/reveille

**Comment by hmemcpy** [comment]
Hey, sorry for the bump. I'm gonna close this. I disabled rss on the blog, so it shouldn't be an issue anymore :)

Thanks for Haskell Weekly!
